### ISSUE TITLE
HOWTO Please (I don't know how to use this plugin)

### ISSUE THREAD

**Issue by isopix** [SteamDeckHomebrew/Mopidy-Controller#1]
Hi,

I was unable to find how to use this plugin:
 - configure it to control remote instance of mopidy?
 - install mopidy locally on SteamDeck? (it's not provided as flatpak and google when asked about "Steam Deck Mopidy" redirects to pages related t your plugin)
 
Sorry, I've never used mopidy (only MPD)

**Comment by marios8543** [comment]
It's meant to control a local instance of mopidy. To install Mopidy on the deck you will need to disable read-only (`sudo steamos-readonly disable`) and install it with pacman. You will then need to configure it as a user service (pretty much take the default systemd service file, change multi-user.target to default.target, and start it with `systemctl --user`)

**Comment by isopix** [comment]
@marios8543 Thak you, didn't expected it will require switching to rw, because PluginLoader didn't required it (not that I'm scared too. Even planned to do it, because all this flatpacked apps[gamehub, minigalaxy] doesn't work fully and takes much, much space.)

I only wonder what does mean that some plugins 'require root'. Do I have to grant special permission, set suid on them or need some special way of manual installation? Or is it only warning and they will install normally and work seamlessly?

Documentation is really lacking basics there...

**Comment by marios8543** [comment]
Replied on discord. As for mopidy I might eventually make an "unofficial" binary release that works out of the box on the deck, because it really wasn't trivial getting it to work, especially Spotify support
